### ISSUE TITLE
"The folder is not a git repository available" for workspaces

### ISSUE THREAD

**Issue by through-a-haze** [jackiotyu/git-worktree-manager#5]
I'm getting the error "The folder is not a git repository available" when trying to "Add Worktree" from an existing workspace.
OS: Windows 10 Pro

From the VSCode output it seems that the extension tries to run the command against the workspace file instead of the folder:
```
[info] 'Running in' g:\projects\my-project\my-project.code-workspace
[info] > git rev-parse --is-inside-work-tree
```

**Comment by jackiotyu** [comment]
This extension currently only supports adding a worktree to a single directory, or you can add the git directory to the git repository management list first, and then add a worktree to the git repository list via the command icon or context menu.

**Comment by jackiotyu** [comment]
<img width="1069" alt="image" src="https://github.com/jackiotyu/git-worktree-manager/assets/31788042/f7ab0134-fd41-44c2-9b8d-cab289b1b417">
Since version 0.3.6, it is possible to add or delete worktrees in the workspace.🤠
