### ISSUE TITLE
[Feature] Name of the folder when add to workspace

### ISSUE THREAD

**Issue by TheFabbiusCorp** [jackiotyu/git-worktree-manager#6]
Hi, amazing project!

I would like to request a tiny feature. I believe that having the name of the worktree folder rather than its absolute path when adding it to the VSC workspace would be cleaner. Of course, many could disagree but it may as well be switched on and off by a checkbox in the settings. Or, if we want to make it more complex to code but easier to handle on the user side, we could let the user choose via prompt the name of the folder when adding it to the workspace.

Thanks so much for this extension!

**Comment by jackiotyu** [comment]
Are you referring to the name of the workspace directory?
This is doable. I'll add a configuration for it later.
![image](https://github.com/user-attachments/assets/1b55da0b-fbb0-4911-a621-3d72d5ebe1f3)

**Comment by jackiotyu** [comment]
![image](https://github.com/user-attachments/assets/30655556-6bf1-49a3-8e2f-dcf04c87363b)
@TheFabbiusCorp Does this meet your requirements?

**Comment by TheFabbiusCorp** [comment]
Yes, that's amazing, thanks 😊

**Comment by jackiotyu** [comment]
This issue has been resolved in 1.0.1.🤠
Feel free to update to the new version, and let me know if you have any feedback or encounter new issues.

**Comment by TheFabbiusCorp** [comment]
@jackiotyu thanks so much for the quick implementation! I will test it today!!

**Comment by TheFabbiusCorp** [comment]
I tested it, it works perfectly, thanks :)
